<?php
$this->headTitle("Aktuelle Jobs bei ".$this->organization->getName());
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination-container.js'));
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination.js'));
/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();
?>
<style>
    
 .nav>li>a {
     position: relative;
    display: block;
    padding: 15px 5px;
    margin-left: 15px;
}

.nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
    /* color: #555; */
    background-color: #fff;
    border-bottom: 2px solid #ddd;
    border-bottom-color: #243b84;
    cursor: default;
    border-top:none;
     border-left:none;
      border-right:none;
}
.nav-tabs>li>a:hover {
    border-color: transparent;
}

.organizationtitle {
    
    border-bottom: 1px solid #dcdfe2;
    padding: 0 15px;
    background-color: #f5f5f5;
    padding-bottom: 15px;
    padding-top: 15px;
    margin-bottom: 0px;
    margin-top: 0px;
}



</style>

<div class="row">
    <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-body">
               <div class="row">
                <div class="col-md-2">
                    <div style="margin-top:20px">
                        
                        <?php if($organization->getImages()->notEmpty('images')): ?>
                          <img src="<?php echo $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail'))) ?>">
                            <?php else: ?>
                             <span class="yk-icon fa-file-image-o fa-5x"></span>
                           <?php endif;?>
                    </div>
 
                </div>
                
                 <div class="col-md-10">
                      <h1 style="font-weight:700;"><?php echo $organization->getName()?></h1>
                      <p><?php echo $contact->getCity()?> </p>
                 </div>
               </div>   
           </div>
           
           <div style="border-top: 1px solid #dcdfe2;">
               
                  <ul class="nav nav-tabs" style="border-bottom:1px solid transparent">
			         <li>
                       <a href="#profil" data-toggle="tab">Überblick</a>
		             </li>
			         <li class="active">
			            <a href="#jobs" data-toggle="tab">Jobs <span class="badge" style="background-color: #243b84;"><?=$this->jobs->getTotalItemCount()?></span></a>
		           	</li>
		          </ul>
 
           </div>
           
       </div>
       <div class="tab-content ">
			  <div class="tab-pane row" id="profil">
			      <div class="col-md-8">
			            <?php if($organization->getdescription()): ?>
                        
                         <div class="panel panel-default">
			               <h4 class="organizationtitle">Über uns</h4>
			               <div class="panel-body">
                            <p><?php echo $organization->getdescription()?></p>
      			          </div>
			             </div> 
                       <?php else: ?>
                       <?php endif;?>
                       
                       
                    <?php if($contact->getStreet()): ?>
                        
                      <div class="panel panel-default">
			           <h4 class="organizationtitle">Adresse</h4>
			             <div class="panel-body">
			            
			             
       
                             <address>
                                <?php echo $contact->getStreet()?> <?php echo $contact->getHouseNumber()?><br/>
                                <?php echo $contact->getCity()?> <?php echo $contact->getPostalcode()?><br/>
                                <?php echo $contact->getCountry()?><br/>
                                <?php echo is_null($contact->getPhone()) ? "":"Telefon: ".$contact->getPhone()."<br/>" ?>
                                <?php echo is_null($contact->getFax()) ? "":"Fax: ".$contact->getFax()."<br/>" ?>
                             </address>
			        </div>
			        
			        
			          
			       </div>
                      
                      
                       <?php else: ?>
                       <?php endif;?>
                       
                       
                     <?php if($contact->getStreet()): ?>
                    
                       <div class="panel panel-default">
			               <h4 class="organizationtitle">Standort</h4>
			            
			                 <iframe src="https://www.google.com/maps?q=Diemelstrasse%202-4,%2060486%20Frankfurt%20am%20Main" />
			        
			          
			         </div> 
                       <?php else: ?>
                       <?php endif;?>

			      </div>
				</div>
				<div class="tab-pane active" id="jobs">
				    
				    
                        <div id="jobs-list-container" class="pagination-container">
                            <div class="pagination-content">
                                <?php echo $this->render('organizations/profile/detail.ajax')?>
                            </div>
                        </div>


				</div>
			</div>
  </div> 
</div>
