<?php
$this->headTitle("Aktuelle Jobs bei ".$this->organization->getName());
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination-container.js'));
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination.js'));
/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();
?>
<div class="row">
    <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-body">
               <div class="row">
                <div class="col-md-2">
                    <div style="margin-top:20px">
                        
                        <?php if($organization->getImages()->notEmpty('images')): ?>
                          <img src="<?php echo $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail'))) ?>">
                            <?php else: ?>
                             <span class="yk-icon fa-file-image-o fa-5x"></span>
                           <?php endif;?>
                    </div>
 
                </div>
                
                 <div class="col-md-10">
                    
                    
                      <h1 style="font-weight:700;"><?php echo $organization->getName()?></h1>
        
                          <p><?php echo $organization->getdescription()?></p>
       
                             <address>
                                <?php echo $contact->getStreet()?> <?php echo $contact->getHouseNumber()?><br/>
                                <?php echo $contact->getCity()?> <?php echo $contact->getPostalcode()?><br/>
                                <?php echo $contact->getCountry()?><br/>
                                <?php echo is_null($contact->getPhone()) ? "":"Telefon: ".$contact->getPhone()."<br/>" ?>
                                <?php echo is_null($contact->getFax()) ? "":"Fax: ".$contact->getFax()."<br/>" ?>
                             </address>
                   
                      </div>
               </div>   
           </div>
           
           <div style="border-top: 1px solid #dcdfe2;" class="panel-body">
               
               
               <input id="tab1" type="radio" name="tabs" checked>
               <label for="tab1">Codepen</label>
    
                <input id="tab2" type="radio" name="tabs">
                <label for="tab2">Dribbble</label>
                    
                <input id="tab3" type="radio" name="tabs">
                <label for="tab3">Dropbox</label>
                    
                <input id="tab4" type="radio" name="tabs">
                <label for="tab4">Drupal</label>
                    
               Jobs <span style="display: inline-block;
                    min-width: 15px;
                    font-size: 14px;
                    color: #fff;
                    line-height: 1;
                    vertical-align: middle;
                    white-space: nowrap;
                    text-align: center;
                    background-color: #243b84;
                    border-radius: 3px;
                    font-size: 10px;
                    font-weight: 600;
                    padding: 3px 6px 4px 6px;
                "><?=$this->jobs->getTotalItemCount()?></span>
               
           </div>
           
       </div>
       
        <section id="content1">
    <p>
      Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
    </p>
    <p>
      Brisket meatball turkey short loin boudin leberkas meatloaf chuck andouille pork loin pastrami spare ribs pancetta rump. Frankfurter corned beef beef tenderloin short loin meatloaf swine ground round venison.
    </p>
  </section>
    
  <section id="content2">
    <p>
      Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken. Pork belly meatball t-bone bresaola tail filet mignon kevin turkey ribeye shank flank doner cow kielbasa shankle. Pig swine chicken hamburger, tenderloin turkey rump ball tip sirloin frankfurter meatloaf boudin brisket ham hock. Hamburger venison brisket tri-tip andouille pork belly ball tip short ribs biltong meatball chuck. Pork chop ribeye tail short ribs, beef hamburger meatball kielbasa rump corned beef porchetta landjaeger flank. Doner rump frankfurter meatball meatloaf, cow kevin pork pork loin venison fatback spare ribs salami beef ribs.
    </p>
    <p>
      Jerky jowl pork chop tongue, kielbasa shank venison. Capicola shank pig ribeye leberkas filet mignon brisket beef kevin tenderloin porchetta. Capicola fatback venison shank kielbasa, drumstick ribeye landjaeger beef kevin tail meatball pastrami prosciutto pancetta. Tail kevin spare ribs ground round ham ham hock brisket shoulder. Corned beef tri-tip leberkas flank sausage ham hock filet mignon beef ribs pancetta turkey.
    </p>
  </section>
    
  <section id="content3">
    <p>
      Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
    </p>
    <p>
      Brisket meatball turkey short loin boudin leberkas meatloaf chuck andouille pork loin pastrami spare ribs pancetta rump. Frankfurter corned beef beef tenderloin short loin meatloaf swine ground round venison.
    </p>
  </section>
    
  <section id="content4">
    <p>
      Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken. Pork belly meatball t-bone bresaola tail filet mignon kevin turkey ribeye shank flank doner cow kielbasa shankle. Pig swine chicken hamburger, tenderloin turkey rump ball tip sirloin frankfurter meatloaf boudin brisket ham hock. Hamburger venison brisket tri-tip andouille pork belly ball tip short ribs biltong meatball chuck. Pork chop ribeye tail short ribs, beef hamburger meatball kielbasa rump corned beef porchetta landjaeger flank. Doner rump frankfurter meatball meatloaf, cow kevin pork pork loin venison fatback spare ribs salami beef ribs.
    </p>
    <p>
      Jerky jowl pork chop tongue, kielbasa shank venison. Capicola shank pig ribeye leberkas filet mignon brisket beef kevin tenderloin porchetta. Capicola fatback venison shank kielbasa, drumstick ribeye landjaeger beef kevin tail meatball pastrami prosciutto pancetta. Tail kevin spare ribs ground round ham ham hock brisket shoulder. Corned beef tri-tip leberkas flank sausage ham hock filet mignon beef ribs pancetta turkey.
    </p>
  </section>
       
       
       
  </div> 
</div>
<div id="jobs-list-container" class="pagination-container"
    <div class="pagination-content">
        <?php echo $this->render('organizations/profile/detail.ajax')?>
    </div>
</div>