<?php
$this->headTitle("Aktuelle Jobs bei ".$this->organization->getName());
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination-container.js'));
$this->headScript()->appendFile($this->basePath('Core/js/core.pagination.js'));
/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();
?>
<div class="row">
    <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-body">
               
                <div class="col-md-2">
                    <div itemprop="logo" style="text-align:center; margin-bottom:15px">
                    <div style=" 
                      margin: 0 auto;
                      width: 115px;
                      height: 115px;   
                      transition: border .2s ease-in-out;
                      position: relative;
                      display: block;
                      padding: 4px;
                      line-height: 1.5;
                      background-color: #fff;
                      border: 1px solid #ddd;
                      border-radius: 3px;
                    overflow: hidden;">
                     <?php if($organization->getImages()->notEmpty('images')): ?>
                          <img style="
                         margin-bottom: auto;
                         text-align: center;
                         width: 65%;
                         position: absolute;
                         top: 5%;
                         bottom: 5%;
                         left: 5%;
                         right: 5%;
                         margin: auto;" src="<?php echo $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail'))) ?>">
                            <?php else: ?>
                             <span class="yk-icon fa-file-image-o fa-5x"></span>
                     <?php endif;?>
                      </div> 
                    </div>
                </div>
                
                 <div class="col-md-10">
                    
                    
        <h1><?php echo $organization->getName()?></h1>
        
        <p><?php echo $organization->getdescription()?></p>
       
        <address>
            <?php echo $contact->getStreet()?> <?php echo $contact->getHouseNumber()?><br/>
            <?php echo $contact->getCity()?> <?php echo $contact->getPostalcode()?><br/>
            <?php echo $contact->getCountry()?><br/>
            <?php echo is_null($contact->getPhone()) ? "":"Phone: ".$contact->getPhone()."<br/>" ?>
            <?php echo is_null($contact->getFax()) ? "":"Fax: ".$contact->getFax()."<br/>" ?>
        </address>
                    
                </div>
                
                  
       
   
 
 
           
           </div>
       </div>

        
     


  </div> 
</div>
<div id="jobs-list-container" class="pagination-container"
    <div class="pagination-content">
        <?php echo $this->render('organizations/profile/detail.ajax')?>
    </div>
</div>
