<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


$this->headTitle('Kostenlos Einzelinserat aufgeben');
?>

<h1>Einzelinserat aufgeben</h1>
<hr />

<?php if ($this->isProcessed):?>
        <div class="row">
            <div class="col-md-7"><h2><?=$this->title?><br><small><?= $this->invoiceAddress['company']?></small></h2></div>
            <div class="col-md-5"><p><?php

                foreach ($this->locations as $loc) {
                    $location = new \Jobs\Entity\Location($loc);
                    echo $location->getCity() . '<br>';
                }
                    ?></p></div>
                    
        </div>
        <div class="row">
            <?php if ('html' == $this->details['mode']):?>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Stellenbeschreibung</h3>
                        </div>
                        <div class="panel-body">
                            <?=$this->details['position']?>

                            <?php $image=isset($this->details['image']['entity'])
                                         ? $this->details['image']['entity'] : null;
                            if ($image):?>
                                <hr>
                                <img src="<?=$this->basePath($image->getUri())?>">
                                <?php endif?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Unternehmensbeschreibung</h3>
                        </div>
                        <div class="panel-body">
                            <?=$this->details['description']?>
                            <?php $logo=isset($this->details['logo']['entity'])
                                ? $this->details['logo']['entity'] : null;
                            if ($logo):?>
                                <hr>
                                <img src="<?=$this->basePath($logo->getUri())?>">
                            <?php endif?>
                        </div>
                    </div>
                </div>
            <?php else: ?>
            <div class="col-md-12"><?= $this->uri ?></div>
            <?php endif ?>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-12"><h3>Rechnungsanschrift </h3></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <address>
                    <?=$this->invoiceAddress['company']?><br>
                    <?=$this->invoiceAddress['name']?> ( <?=$this->link($this->invoiceAddress['email']) ?> )<br><br>
                    <?=$this->invoiceAddress['street']?> <?=$this->invoiceAddress['houseNumber']?><br>
                    <?=$this->invoiceAddress['zipCode']?> <?=$this->invoiceAddress['city']?><br>
                    <?=$this->invoiceAddress['region'] ?>, <?=$this->invoiceAddress['country']?>
                </address>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <a class="btn btn-primary" href="?do=complete">Einzelinserat jetzt schalten</a>
            </div>
        </div>
<?php elseif ($this->isSuccess): ?>
    <?=$this->alert()->success('Inserat erfolgreich angelegt.');?>
    <p class="lead">Vielen Dank</p>
    <p>Ihre Anzeige wurde angelegt. Nach der Prüfung ... wird sie freigeschaltet.</p>
<?php elseif ($this->isError): ?>
    <?=$this->alert()->danger('Inserat anlegen fehlgeschlagen');?>
    <p class="lead">Das Inserat konnte nicht angelegt werden.</p>
<p>Es ist ein Fehler aufgetreten. Versuchen Sie es <a href="">erneut</a> ...</p>
<?php else: ?>
<div class="container"><div class="row"><div class="col-md-12">
            <?=$this->form($this->form->setAttribute('data-handle-by', 'native'))?>
</div></div></div>
<?php endif ?>



