<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$form = $this->element;
$this->headScript()->appendFile($this->basePath('Gastro24/create-single-job.js'));
?>


<?=$this->form()->openTag($form)?>
<?=$this->formRow($form->get('title'), null, null, 'form-horizontal')?>
<?=$this->formRow($form->get('locations'))?>
<?php $mode = $form->get('mode'); $isUri = 'uri' == $mode->getValue(); ?>
<div class="controls controls-row form-group">
    <div class="col-md-3 yk-label">&nbsp;</div>
    <div class="col-md-3" id="csj-mode-uri-span">
        <input type="radio" id="csj-mode-uri" name="mode" value="uri" <?=$isUri ? 'checked' : ''?>> <label for="csj-mode-uri">URL angeben.</label>
    </div>
    <div class="col-md-4" id="csj-mode-pdf-span">
        <input type="radio" id="csj-mode-pdf" name="mode" value="pdf" <?=$isUri ? '' : 'checked' ?>> <label for="csj-mode-pdf"> PDF-Datei hochladen.</label>
    </div>
</div>
<?=$this->formRow($form->get('uri'))?>
<?=$this->formRow($form->get('pdf'))?>
<?=$this->formCollection($form->get('invoiceAddress'))?>
<div class="controls controls-row form-group"><div class="col-md-12 text-right">
        <?=$this->formCollection($form->get('buttons'))?>
    </div></div>
<?=$this->form()->closeTag($form)?>



