<?php //description: Renders the list of public jobs. ?>
<?php
$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination-container.js'))
     ->appendFile($this->basePath('Core/js/core.forms.js'))
     ->appendFile($this->basePath('assets/select2/js/select2.min.js'))
     ->appendFile($this->basePath('Gastro24/jquery.matchHeight.js'))
     ->appendFile($this->basePath('Gastro24/jobs.js'));;
if ($this->params('lang') != 'en') {
    $this->headScript()->appendFile($this->basePath('assets/select2/js/i18n/' . $this->params('lang') . '.js'))
                       ->appendFile($this->basePath('/assets/bootstrap3-dialog/js/bootstrap-dialog.min.js'));
}
$this->headLink()->appendStylesheet($this->basePath('assets/select2/css/select2.css'))
?>
<?php

$queryGet = $this->params()->fromQuery();
unset($queryGet['clear']);
$query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
$wordpress = $this->proxy('wordpress');

$this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
$this->headMeta()->setName('keywords', $wordpress->call('value', ['meta-fields.keywords'], ''));
$description = $wordpress->call('value', ['content.rendered'], '');

$title = $wordpress->call('value', ['meta-fields.title'], '');
$this->headTitle($title ?: $this->translate('Jobs'));

$robots = "noindex,follow";
if (304 === $query || ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage') && (count($this->jobs) || $description))) {
    $robots = substr($robots, 2);
}
$this->headMeta()->setName('robots', $robots);
$this->headScript()->captureStart();
?>
(function($) {

    $(function() {
        var $tabbar = $('#search-tabs');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24 g24-jobs:init', function(ev) {
            $tabbar.show();
            var html = $('#jobs-list-container').find('.pagination-content').html();

            if ('' === html.trim()) { $tabbar.hide(); }

            $('#jobs-list-container ul.pagination a, link[rel="prev"], link[rel="next"]').each(function() {
                var $a = $(this), href = $a.attr('href');
                console.debug($a, href);
                if (href) {
                    href = href.replace(/__region_MultiString/, 'r')
                               .replace(/__city_MultiString/, 'l')
                               .replace(/__organizationTag/, 'c')
                               .replace(/__industry_MultiString/, 'i')
                               .replace(/__employmentType_MultiString/, 't');
                    $a.attr('href', href);
                }
            });


        }).trigger('g24-jobs:init');

        var $jobCount = $('#job-count');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24-job-count', function(ev) {
            var count = $('#update-job-count').text();
            $jobCount.text(count);
        });

        $('#jobs-list-filter').on('reset.gastro24', function(ev) { $(ev.target).find('input.facet-param').remove(); });

    });
})(jQuery);
<?php $this->headScript()->captureEnd();?>

<?php if ($jobs instanceof \Solr\FacetsProviderInterface): $this->headScript()->appendFile($this->basePath('Gastro24/jobs.facets.js')); endif; ?>



<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>

<nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
    <div class="search-form-container">
        <?php
            $queryParams = $this->params()->fromQuery();
            foreach (array_keys($this->jobs->getFacets()->toArray()) as $facetName):
                if (isset($queryParams['__' . $facetName])) {
                    $facetValues = explode('_', $queryParams['__' . $facetName]);
                    $facetValues = array_fill_keys($facetValues, '1');
                    $queryParams[$facetName] = $facetValues;
                }
                if (isset($queryParams[$facetName])):
                    foreach (array_keys($queryParams[$facetName]) as $facetValue):
                        $this->filterForm->add(['type' => 'hidden', 'name' => $facetName . '[' . $facetValue . ']',
                                                'attributes' => ['class' => 'facet-param', 'value' => 1]]);
                    endforeach;
                endif;
            endforeach;$this->filterForm->setButtonElement('q');
            //$this->filterForm->add( ['type' => 'hidden', 'name' => 'clear', 'attributes' => ['value' => 1]]);
            $this->filterForm->setAttribute('data-handle-by', 'native');
            $this->filterForm->setAttribute('action', $this->url('lang/jobboard', [], true));
             echo $this->searchForm($this->filterForm)  ?>
    </div>
</nav>
  <div class="container">
     <div class="row">
	     <div class="header-tab-bar" style="padding:25px 0">
		 
             <h1 class="text-center"> <?=$wordpress->call('value', ['title.rendered'], '') ?: (count($this->jobs) ? 'Jobs gefunden' : 'Leider keine passenden Jobs gefunden'); ?></h1>
             <?php $parts=preg_split('~<!--more-->~' , $description);?>
			 <p class="similar-jobs text-center"><?=$parts[0]?></p>
		 </div>
	 </div>
 </div>
<div class="container" style="margin-bottom: 20px;">
    <div class="row">
            <ul id="search-tabs" class="nav nav-pills" style="padding:0 30px">
                <li class="active">
                    <a data-toggle="tab" href="#jobs-list-container"><span id="job-count"><?=$this->jobs->getTotalItemCount()?></span> Offene Stellen</a>
                </li>
                <?php if (isset($parts[1]) && ""!=trim($parts[1])): ?><li><a href="#taetigkeit">Tätigkeit</a></li><?php endif ?>
                <?php if (isset($parts[2]) && ""!=trim($parts[2])): ?><li><a href="#lohn">Lohn</a></li><?php endif ?>
                <?php if (isset($parts[3]) && ""!=trim($parts[3])): ?><li><a href="#karriere-weiterbildung">Karriere & Weiterbildung</a></li><?php endif ?>
                <?php if (isset($parts[4]) && ""!=trim($parts[4])): ?><li><a href="#erfahrungsberichte">Erfahrungsberichte</a></li><?php endif ?>
            </ul>
    </div>
</div>
<?php if (!count($this->jobs)):?>
    <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
    <script type="text/javascript">
        ;(function($) {
            $(function() {
                $('#form-jobsbymail-subscribe-form').find('button.btn-info').hide().click()
                    .end().find('#job-by-mail-subscribe-label').html('Informiert werden, sobald Jobs zu Ihrer Suchanfrage verfügbar sind.');
            });
        })(jQuery);
    </script>
<?php endif ?>
<div class="container">
    <div class="row">
        <div class="tab-content">
            <div id="jobs-list-container" class="pagination-container"
                 data-message="<?php echo $this->escapeHtmlAttr(sprintf(
                                                                    $this->translate('%sSorry%s, there are not any jobs matching your search criteria.'
                                                                    ),
                                                                    '<strong>', '</strong>'
                                                                )
                 ) ?>"
                 data-uri="<?php
                 echo $this->url('lang/jobboard', array(), array('query' => $this->params()->fromQuery()), true) ?>">

                <!--   <h3>Insgesamt <span id="job-count"><?= $this->jobs->getTotalItemCount(
                ) ?></span> freie Stellen zur Auswahl</h3>-->

                <div class="pagination-message alert alert-warning">
                    <?=sprintf(
                           $this->translate('%sSorry%s, there are not any jobs matching your search criteria.'
                           ),
                           '<strong>', '</strong>'
                       )?>
                </div>

                <div class="pagination-content">
                    <?php echo $this->render('jobs/jobboard/index.ajax.phtml') ?>
                </div>
            </div>
            <?php if (isset($parts[1]) && "" != trim($parts[1])): ?>
                <div id="taetigkeit" >
                    <?= $parts[1] ?>
                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                </div>
            <?php endif ?>
            <?php if (isset($parts[2]) && "" != trim($parts[2])): ?>
                <div id="lohn" >
                    <?= $parts[2] ?>
                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                </div>
            <?php endif ?>
            <?php if (isset($parts[3]) && "" != trim($parts[3])): ?>
                <div id="karriere-weiterbildung" >
                    <?= $parts[3] ?>
                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                </div>
            <?php endif ?>
            <?php if (isset($parts[4]) && "" != trim($parts[4])): ?>
                <div id="erfahrungsberichte >
                    <?= $parts[4] ?>
                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>


<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
            </div>
        </div>
    </div>
