<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
if (count($jobs)): // We only want to render something, if there are items.
?><div class="hidden" id="update-job-count"><?=$this->jobs->getTotalItemCount()?></div><?php
$hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;

$queryGet = $this->params()->fromQuery();
unset($queryGet['clear']);
$query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
$wordpress = $this->proxy('wordpress');

$this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
$this->headMeta()->setName('keywords', $wordpress->call('value', ['meta-fields.keywords'], ''));
$description = $wordpress->call('value', ['content.rendered'], '');


?>
  <button type="button" class="hidden visible-sm visible-xs pull-right btn btn-secondary" aria-expanded="false" data-toggle="collapse" data-target=".panel-group">Filter anzeigen
              </button>
    <div class="row">

    <div class="col-md-3">
        <div style="margin-bottom:30px">
            <strong class="h4" style="color:#22436c"><?=$this->jobs->getTotalItemCount()?> Treffer für</strong>
            <h1 style="display:inline;color:#22436c" class="h4">
                <?=$wordpress->call('value', ['title.rendered'], '') ?: (count($this->jobs) ? 'Ihre Job-Suche' : 'Leider keine passenden Jobs gefunden'); ?>
            </h1>
	  </div>
	<?php if ($hasFacets):
    if ($this->params()->fromRoute('isLandingPage')):?>
        <span class="facets-url" data-url="<?=$this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true)?>"></span>
    <?php endif;
    $facets = $jobs->getFacets();
    ?>
    <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
    


    <div class="panel-group collapse dont-collapse-sm">
	
        <?php $facetsHtml = ''; $isFirstFacet = true; $atLeastOneTotalActive = false; foreach ($facets as $facetName => $facetValues):?>
            <?php if(count($facetValues)>0): $atLeastOneActive = false; $facetsList = []; ob_start();?>
            <div id="facets-box-<?=$facetName?>" class="panel panel-default">
                <div class="panel-heading">
                    <a class="<?=$isFirstFacet ?  '%firstCollapsed% ' : '%collapsed%'?>" style="display:block;width: 100%;text-decoration:none;" data-toggle="collapse" data-parent="#facets-box-<?=$facetName?>" href="#facets-box-<?=$facetName?>-content">
                    <?=$this->translate($facets->getTitle($facetName))?>
                        <span class="small">%facetsList%</span>
                    </a>

                </div>
                <div id="facets-box-<?=$facetName?>-content" class="panel-collapse collapse <?=$isFirstFacet ? '%firstIn%' : '%in%' ?>">
                <div class="panel-body">
                    <?php foreach ($facetValues as $facetValue => $facetValueCount):
                        $activeFacet = $facets->isValueActive($facetName, $facetValue);
                        $atLeastOneActive = $atLeastOneActive || $activeFacet;?>
                        <div>
                            <label<?=$activeFacet ? ' class="text-primary"' : ''?>>
                                <input type="checkbox" name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                       class="facet-checkbox"<?=$activeFacet?" checked":""?>>
                                <?=$facetValue?> (<?=$facetValueCount?>)
                            </label>
                        </div>
                    <?php if ($activeFacet): $facetsList[] = $facetValue; endif; endforeach;?>
                </div>
                </div> <!-- facets-collaps-* -->
            </div>
            <?php $facetsHtml .= str_replace(
                    ['%in%', '%firstIn%', '%firstCollapsed%', '%collapsed%', '%facetsList%' ],
                    [
                            $atLeastOneActive ? 'in' : '',
                            $atLeastOneActive ? 'in' : '%firstIn%',
                            $atLeastOneActive ? '' : '%firstCollapsed%',
                            $atLeastOneActive ? '' : 'collapsed',
                            join(', ', $facetsList),
                    ],
                    ob_get_clean()
                ); $atLeastOneTotalActive = $atLeastOneTotalActive || $atLeastOneActive; endif; $isFirstFacet = false;?>
        <?php endforeach;
            echo str_replace(
                    ['%firstCollapsed%', '%firstIn%'],
                    [$atLeastOneTotalActive ? 'collapsed' : '', $atLeastOneTotalActive ? '' : 'in'],
                    $facetsHtml
            );
        ?>

        <div class="panel panel-default">
                <div class="panel-body">
                    <button id="facets-apply" class="btn btn-primary">Filter anwenden</button>
                    <button id="facets-reset" class="btn btn-default pull-right">Löschen</button>
                </div>
        </div>
    </div>
    </div>


    <div class="col-md-9">
        <div class="pull-right">
            <style>
                
                .jssocials-share-logo {

    font-size: 16px;
}
            </style>
            
            <div id="share" class="round-shares"></div>
            <script src="<?=$this->basePath('/Gastro24/jssocials-1.4.0/dist/jssocials.js') ?>"></script>
            <script>
                $("#share").jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["email", "twitter", "facebook", "whatsapp"]
                });
            </script>
        </div>
        <div class="clearfix"></div>
        <hr />
        <div class="row">
    
        
     
            
<?php endif;?>



    <div class="row-eq-height">
    <?php foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */ ?>
    <?php

    $org = $job->getOrganization();
    $href = $this->jobUrl($job, ['linkOnly' => true ]);

    ?>
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="featured-image-box">
            <div class="img-box">
                <a href="<?=$href?>">
                <?php
                $logo = $hasFacets ? $job->getSolrValue('companyLogo') : '';
               
                if (preg_match("/^(https?:)?\/\//",$logo)) { 
                    echo '<img class="yk-logo-sm center-block" src="' . $logo .'">';
		        } elseif ($org && $org->getImage() &&  $org->getOrganizationName()) {
                    echo '<img class="yk-logo-sm center-block" src="';
		            echo $this->basePath($this->organizationImageCache->getUri($job->getOrganization()->getImage(true))) . '">';
                } 
                ?>
                </a>
            </div>
            <div class="content-area">
                <div class="top-cnt">
        
                    <h4>
                        <a title="<?=strip_tags($job->getTitle())?>"
                           href="<?=$href?>">
                            <?=strip_tags($job->getTitle())?>
                        </a>
                    </h4>
                    <p>
                    <?php
                    if ($job->getCompany()) {
			            echo $job->getCompany();
                    } elseif ($org && $org->getOrganizationName() && $org->getOrganizationName()->getName()) {
                        echo $org->getOrganizationName()->getName();
                    }
                    ?>
                    </p>
               <!--     <p>
                        <?php $typeOfContract = $job->getTemplateValues()->get('types')?:'Vollzeit' ?>
                        <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
                    </p>-->
                   <p> Publiziert am:
                        <?php
                        if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                        elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                        endif?>
                    <br /><?=$job->getLocation()?> </p>
                   
                </div>
            </div>
            <div class="apply">
                <?=$this->gastroApplyUrl($job);?>
            </div>
        </div>
 
     </div>
    <?php endforeach?>

    </div>

        </div>
        <?= $this->paginationControl($jobs, 'Sliding', 'pagination-control',
                                     [
                                         'lang' => $this->params('lang'),
                                         'route' => 'lang/jobboard'
                                     ]);
        ?>

    </div>
        <?=$hasFacets ? '</div>' : '' ?>
<?php endif ?>



