<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<script src="<?=$this->basepath('Gastro24/jquery.matchHeight.js')?>" type="text/javascript"></script>
<script type="text/javascript">
   $(function() {
    $('.featured-image-box').matchHeight({
        byRow: true,
        property: 'height',
        target: null,
        remove: false
    });
});

</script>

<?php if (count($jobs)): // We only want to render something, if there are items.?>
    <div class="row-eq-height">
<?php

foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */

    $org = $job->getOrganization();
    ?>
    <?php $href = $job->getLink() ? $job->getLink() : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->getId())), true); ?>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="featured-image-box">
            <div class="img-box"><a title="" href="<?=$href?>">
    <?php if ($org && $org->getImage() &&  $org->getOrganizationName()): ?>
        <img class="yk-logo-sm center-block" src="<?php echo $this->basePath($this->organizationImageCache->getUri($job->organization->image)) ?>">
    <?php endif ?>
                </a></div>
            <div class="content-area">
                <div class="top-cnt">
                    <p class="date">
                        <?php
                        if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                        elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                        endif?>
                    </p>
                    <h4>
                        <a title="<?= strip_tags($job->getTitle())?>" href="<?=$href?>"><?= strip_tags($job->getTitle())?></a>
                    </h4>
                    <?php
    if ($org && $org->getOrganizationName() && $org->getOrganizationName()->getName()) {
        echo $org->getOrganizationName()->getName();
    }
    ?>
                    <p><?php $typeOfContract = $job->getTemplateValues()->get('types')?:'fulltime' ?>
                        <span class="yk-contract yk-<?php echo $typeOfContract?>">
                            <?php echo $typeOfContract; ?>
                        </span>
                    </p>
                    <p><?php echo $job->getLocation()?></p>
                </div>
        <?php
    echo $this->applyUrl($job);
    ?>

            </div>
        </div>
    </div>





<?php endforeach?>
    </div>
    <div class="clear"></div>
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobboard'));?>
<?php endif ?>