<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};
?>

<div class="panel panel-default">
    <div class="panel-body">
        
              <?php /* Firmenlogo */ ?>

                <div itemprop="logo" style="text-align:center">
                    <img src="<?= $template && ($logo = $template->getLogo())
                        ? $this->basePath($logo->getUri())
                        : $this->uriLogo?>" alt="<?= $this->organizationName?>">
                </div>
  
  
     <?php /* Bannerbild */ ?>

        <?php if ($template && ($image = $template->getImage())):?>
        
                <div class="row text-center">
                    <img style="width:100%" src="<?=$this->basePath($image->getUri())?>">
                </div>
            
        <?php endif ?>



        <?php /* Stellenbeschreibung */ ?>

        <div class="row">
            <div class="col-md-12 position">
                <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
            </div>
        </div>
        
       </div>
</div>     


<div class="panel panel-default">
    <div class="panel-body">
                  <?php /* Anforderungen */ ?>
    

                <?=$this->requirements;?>
                
        
  
    </div>
</div>


        
<div class="panel panel-default">
    <div class="panel-body">
        
    
        <?php /* Unternehmensbeschreibung */ ?>
        <p ><?=$this->descriptionEditable ?></p>
        
            <div itemscope itemtype="http://schema.org/Organization">
                <strong itemprop="name">
                    <?= $this->organizationName?>
                </strong><br/>
                <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                    <span itemprop="streetAddress"><?=$this->street?></span><br>
                    <span itemprop="postalCode"><?=$this->postalCode?></span>
                    <span itemprop="addressLocality"><?=$this->city?></span>
                    <br><br>
                    <span itemprop="telephone"><?=$this->phone?></span>
                </address>
            </div>

   </div>
</div>




    <div class="text-center">
           <?=$this->gastroApplyUrl($job);?> 
           
    </div>

