<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

$this->headMeta()->setName('robots', 'index,nofollow');
$this->headTitle($this->job->getTitle());
if (!$this->isVisited):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            7500
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

$orgName = $this->jobOrganizationName($this->job);
?>

<style>
    
    
   .apply-view-extern>a {
    padding: 10px 15px;
    margin-top: 25px;
    font-weight: 300;
    font-size: 16px;
    line-height: 20px;
    color:#fff;
    background-color:#31b0d5;
    display:inline-block;
}
</style>


   
<a href="<?=$href?>">
                <?php
                $logo = $hasFacets ? $job->getSolrValue('companyLogo') : '';
               
                if (preg_match("/^(https?:)?\/\//",$logo)) { 
                    echo '<img class="yk-logo-sm center-block" src="' . $logo .'">';
		        } elseif ($org && $org->getImage() &&  $org->getOrganizationName()) {
                    echo '<img class="yk-logo-sm center-block" src="';
		            echo $this->basePath($this->organizationImageCache->getUri($job->getOrganization()->getImage(true))) . '">';
                } 
                ?>
                </a>



     <h6 style="color:#31b0d5; text-transform:uppercase" class="h3"><?= $orgName ?></h6>
     <h1 style="margin-top:0px;"> <?=$this->job->getTitle()?></h1>
     
     <p> Publiziert am:
                        <?php
                        if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                        elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                        endif?>
                   
                   
         | <?=$job->getLocation()?> | 
                        <?php $typeOfContract = $job->getTemplateValues()->get('types')?:'Vollzeit' ?>
                        <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
              

         

                        
  
   </p>

          <div class="apply-view-extern">
                <?=$this->gastroApplyUrl($job);?>
            </div>
      <hr />

            
        
 
 

<div style="background-color: #fff;padding:15px">


    <p><?php if ($this->isVisited): ?>
                        Sie haben sich diese Stellenanzeige bereits angesehen.
                    <?php else: ?>
                        Sie werden in Kürze automatisch auf das Job-Inserat von <?=$orgName?> weitergeleitet...
                        <br />
                         <strong>Bitte beziehen Sie sich bei Ihrer Bewerbung auf Gastrojob24.ch.</strong>
                         
                         <br />
                         <br />
                         Viel Erfolg bei der Bewerbung!
                    <?php endif ?>
    </p>
<p><a style="text-decoration:underline" href="<?=$this->job->getLink()?>">&raquo; Direkt zum Inserat</a></p>


</div>
<iframe style="border:0" class="col-md-12"  height="1000px" src="<?=$this->job->getLink()?>" scrolling="yes">
</iframe>


