<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

$this->headMeta()->setName('robots', 'index,follow');
$this->headTitle($this->job->getTitle());
$iframeValidator = $this->services('ValidatorManager')->get(\Gastro24\Validator\IframeEmbeddableUri::class);
$link = $this->job->getLink();
$isEmbeddable = $iframeValidator->isValid($link);

if (!$this->isVisited && !$isEmbeddable):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            3000
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

$orgName = $this->jobOrganizationName($this->job);
?>


     <h6 style="color:#31b0d5; text-transform:uppercase" class="h3"><?= $orgName ?></h6>
     <h1 style="margin-top:0px;"> <?=$this->job->getTitle()?></h1>
     
     <p> Publiziert am:
                        <?php
                        if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                        elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                        endif?>
                   
                   
         | <?=$job->getLocation()?> | 
                        <?php $typeOfContract = $job->getTemplateValues()->get('types')?:'Vollzeit' ?>
                        <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
              

         

                        
  
   </p>

                <?=$this->gastroApplyUrl($job);?>


      <hr />

            
        
 
 




 
     <?php if ($this->isVisited && !$isEmbeddable): ?>
  
  
      <div style="background-color: #fff;padding:15px">
                          
                                <p>
                        Sie haben sich diese Stellenanzeige bereits angesehen.
                        
                        <p><a style="text-decoration:underline" href="<?=$this->job->getLink()?>">&raquo; Direkt zum Inserat</a></p>
                        
                        </div>
                
                        
                    <?php elseif (!$isEmbeddable): ?>
                    
                    <style>
                        
                         .spinner {
  margin: 0 auto;
  width: 70px;
  text-align: center;
}

.spinner > div {
  width: 18px;
  height: 18px;
  background-color: #333;

  border-radius: 100%;
  display: inline-block;
  -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  animation: sk-bouncedelay 1.4s infinite ease-in-out both;
}

.spinner .bounce1 {
  -webkit-animation-delay: -0.32s;
  animation-delay: -0.32s;
}

.spinner .bounce2 {
  -webkit-animation-delay: -0.16s;
  animation-delay: -0.16s;
}

@-webkit-keyframes sk-bouncedelay {
  0%, 80%, 100% { -webkit-transform: scale(0) }
  40% { -webkit-transform: scale(1.0) }
}

@keyframes sk-bouncedelay {
  0%, 80%, 100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  } 40% { 
    -webkit-transform: scale(1.0);
    transform: scale(1.0);
  }
}

                    </style>
                      
                      
                 
                    <div style="background-color: #fff;padding:15px">
                        
                           <div class="spinner">
  <div class="bounce1"></div>
  <div class="bounce2"></div>
  <div class="bounce3"></div>
</div>
                        <p>
                        Sie werden in Kürze automatisch auf das Job-Inserat von <?=$orgName?> weitergeleitet...
                        <br />
                         <strong>Bitte beziehen Sie sich bei Ihrer Bewerbung auf Gastrojob24.ch.</strong>
                         
                         <br />
                         <br />
                         Viel Erfolg bei der Bewerbung!</p>
                         
                         </div>
                         
                    <?php endif ?>
    





<?php if ($isEmbeddable):?>
<style>
#preload {
    
    
    background-color:#fff;
    padding:100px 0;
    margin:10px 0;
}
    
    .frame-content {
        
        
        position: relative; 
  padding-bottom: 56.25%; /* ratio 16x9 */
  height: 0; 
  overflow: hidden; 
  width: 100%;
  height: auto;
    }
    
    .frame-content iframe {
        
        border: 1px solid #ccc;

 background-color:#fff;
        
       
        margin:10px 0;
         position: absolute; 
  top: 0; 
  left: 0; 
  width: 100%; 
  height: 100%;
    }
    
    .spinner {
  margin: 0 auto;
  width: 70px;
  text-align: center;
}

.spinner > div {
  width: 18px;
  height: 18px;
  background-color: #333;

  border-radius: 100%;
  display: inline-block;
  -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  animation: sk-bouncedelay 1.4s infinite ease-in-out both;
}

.spinner .bounce1 {
  -webkit-animation-delay: -0.32s;
  animation-delay: -0.32s;
}

.spinner .bounce2 {
  -webkit-animation-delay: -0.16s;
  animation-delay: -0.16s;
}

@-webkit-keyframes sk-bouncedelay {
  0%, 80%, 100% { -webkit-transform: scale(0) }
  40% { -webkit-transform: scale(1.0) }
}

@keyframes sk-bouncedelay {
  0%, 80%, 100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  } 40% { 
    -webkit-transform: scale(1.0);
    transform: scale(1.0);
  }
}

</style>


<script type="text/javascript">
$(function(){var d=15,a=$("#preload").removeClass("hidden"),e=$(".frame-content iframe").addClass("hidden"),c=$(window),g=$("header"),f=$("footer"),b=$(".box.intro");setTimeout(function(){a.addClass("hidden");e.removeClass("hidden")},3000);c.resize(function(){e.height(c.height()-g.outerHeight(true)-f.outerHeight(true)-b.outerHeight(true)-d)}).resize()});
</script>
<!-- PRELOAD<script>
function setIframeSrc() {
  var s = "";
  var iframe1 = document.getElementById('iframe1');
  if ( -1 == navigator.userAgent.indexOf("MSIE") ) {
    iframe1.src = s;
  }
  else {
    iframe1.location = s;
  }
}
setTimeout(setIframeSrc, 5);
</script>-->


 <div class="hidden-sm hidden-md hidden-lg text-center" style="background-color: #fff;padding:15px">
   <a href="<?=$this->job->getLink()?>">&raquo; Direkt zum Inserat</a>

</div>
<div class="hidden-xs frame-content ">
     <div id="preload" class="loading hidden text-center">
         
         <div class="spinner">
  <div class="bounce1"></div>
  <div class="bounce2"></div>
  <div class="bounce3"></div>
</div>
         
         <p>Das inserat wird geladen, bitte haben Sie einem Moment Geduld</p>

      </div>
      
      
<iframe id="iframe1" frameborder="0" allowfullscreen src="<?=$this->job->getLink()?>"></iframe>
      


</div>




<?php endif; ?>


