<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

$this->headMeta()->setName('robots', 'index,nofollow');
$this->headTitle($this->job->getTitle());
$iframeValidator = $this->services('ValidatorManager')->get(\Gastro24\Validator\IframeEmbeddableUri::class);
$link = $this->job->getLink();
$isEmbeddable = $iframeValidator->isValid($link);

if (!$this->isVisited && !$isEmbeddable):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            3000
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

$orgName = $this->jobOrganizationName($this->job);
?>


     <h6 style="color:#31b0d5; text-transform:uppercase" class="h3"><?= $orgName ?></h6>
     <h1 style="margin-top:0px;"> <?=$this->job->getTitle()?></h1>
     
     <p> Publiziert am:
                        <?php
                        if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                        elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                        endif?>
                   
                   
         | <?=$job->getLocation()?> | 
                        <?php $typeOfContract = $job->getTemplateValues()->get('types')?:'Vollzeit' ?>
                        <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
              

         

                        
  
   </p>

                <?=$this->gastroApplyUrl($job);?>


      <hr />

            
        
 
 

<div style="background-color: #fff;padding:15px">


    <p><?php if ($this->isVisited): ?>
                        Sie haben sich diese Stellenanzeige bereits angesehen.
                    <?php elseif (!$isEmbeddable): ?>
                        Sie werden in Kürze automatisch auf das Job-Inserat von <?=$orgName?> weitergeleitet...
                        <br />
                         <strong>Bitte beziehen Sie sich bei Ihrer Bewerbung auf Gastrojob24.ch.</strong>
                         
                         <br />
                         <br />
                         Viel Erfolg bei der Bewerbung!
                         
                    <?php endif ?>
    </p>

<p><a style="text-decoration:underline" href="<?=$this->job->getLink()?>">&raquo; Direkt zum Inserat</a></p>

</div>

<?php if ($isEmbeddable):?>
<style>
    
    .frame-content,.frame-content iframe{position:relative;width:100%;height:100%;margin:0;padding:0;border:0 none;background:none #ffffff}

</style>


<script type="text/javascript">
$(function(){var d=15,a=$("#preload").removeClass("hidden"),e=$(".frame-content iframe").addClass("hidden"),c=$(window),g=$("header"),f=$("footer"),b=$(".box.intro");setTimeout(function(){a.addClass("hidden");e.removeClass("hidden")},2000);c.resize(function(){e.height(c.height()-g.outerHeight(true)-f.outerHeight(true)-b.outerHeight(true)-d)}).resize()});
</script>

<script>
function setIframeSrc() {
  var s = "<?=$this->job->getLink()?>";
  var iframe1 = document.getElementById('iframe1');
  if ( -1 == navigator.userAgent.indexOf("MSIE") ) {
    iframe1.src = s;
  }
  else {
    iframe1.location = s;
  }
}
setTimeout(setIframeSrc, 5);
</script>
<div class="frame-content ">
<div id="preload" class="loading hidden text-center">
<p>
<span class="glyphicon glyphicon-repeat"></span>
</p>
<p>
Das Inserat wird geladen. Bitte warten...
</p>
</div>
<iframe id="iframe1"  style="width:100%; background-color:#fff;" frameborder="0" class="iframe-placeholder"  height="600px" src="" scrolling="yes">
</iframe>

</div>




<?php endif; ?>


