<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};
$orgName = $this->jobOrganizationName($this->job);
?>



  <div class="panel panel-default">
    <div class="panel-body">
    
  
     <?php /* Bannerbild */ ?>

        <?php if ($template && ($image = $template->getImage())):?>
        
                <div class="row text-center">
                    <img style="width:100%; margin-bottom:15px;margin-top:-15px" src="<?=$this->basePath($image->getUri())?>">
                </div>
            
        <?php endif ?>



        <?php /* Stellenbeschreibung */ ?>

        <div class="row">
            <div class="col-md-12 position">
                <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
            </div>
        </div>
 


                  <?php /* Anforderungen */ ?>
    

                <?=$this->requirements;?>
                
        
  


        

        
    
        <?php /* Unternehmensbeschreibung */ ?>
        <p ><?=$this->descriptionEditable ?></p>
        
            <div itemscope itemtype="http://schema.org/Organization">
                <strong itemprop="name">
                    <?= $this->organizationName?>
                </strong><br/>
                <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                    <span itemprop="streetAddress"><?=$this->street?></span><br>
                    <span itemprop="postalCode"><?=$this->postalCode?></span>
                    <span itemprop="addressLocality"><?=$this->city?></span>
                    <br><br>
                    <span itemprop="telephone"><?=$this->phone?></span>
                </address>
            </div>

   </div>
</div>

  <div class="panel panel-default"> 
      <div class="panel-body"> 
         <div id="share" class="text-center round-shares"></div>
       </div >
   </div>


    <div class="text-center">
           <?=$this->gastroApplyUrl($job);?> 
           
    </div>
    
    
     <style>
        .round-shares .jssocials-share-link {
            border-radius: 50%;
        }
    </style>
</head>
    

            <script src="/Gastro24/jssocials-1.4.0/dist/jssocials.js"></script>
            <script>
                $("#share").jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["email", "twitter", "facebook", "whatsapp"]
                });
            </script>
    
    
  </div>
</div>
<!-- ENDE COL MD 9-->

<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
        
   <?php /* Firmenlogo */ ?>

                <div itemprop="logo" style="text-align:center; margin-bottom:15px">
                    <img src="<?= $template && ($logo = $template->getLogo())
                        ? $this->basePath($logo->getUri())
                        : $this->uriLogo?>" alt="<?= $this->organizationName?>">
                </div>
                
                <h2 class="text-center"><?= $orgName ?></h2>
                
                <!--<div style="margin-bottom:5px" class=""><a href="" class="btn btn-default btn-block company-jobs-btn"><strong>Unternehmensporträt</strong></a></div>
                 <div class=""><a href="" class="btn btn-default btn-block company-jobs-btn">3 Jobs</a></div>-->
       </div>
    </div>
</div>


