<!DOCTYPE html>
<html>
<head>
        <?=$this->jsonLd($this->job)?>
    <title><?=$this->headTitle?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta property="og:url" content="<?= $this->uriJob;?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->headTitle; ?> - <?= $this->organizationName;?>" />
     <link rel="stylesheet" href="<?php echo $this->basePath("/Gastro24/Gastro24.css")?>" type="text/css">
    <style>
        .col-md-3, .internal-apply-link {display:none;}
        .panel {margin-bottom: 0px;border: 1px solid transparent;}
        .panel-body {padding-left:15px;padding-right:15px;padding-top:0px;padding-bottom:0px;}

    </style>
</head>
<body>
<div class="row">
    <div class=container >
      <div class="row">
       <div class="col-md-9" >
      
          <?=$this->render('gastro24/jobs/view-intern');?>
        </div>
    </div>
  </div>
 </div>
</body>
</html>
