<!DOCTYPE html>
<html>
<head>
        <?=$this->jsonLd($this->job)?>
    <title><?=$this->headTitle?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta property="og:url" content="<?= $this->uriJob;?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->headTitle; ?> - <?= $this->organizationName;?>" />
    <style>
        .col-md-3, .internal-apply-link {display:none;}

    </style>
</head>
<body>
    <?=$this->render('gastro24/jobs/view-intern');?>
</body>
</html>
