<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \JobsByMail\Entity\SearchProfileInterface $searchProfile */
$searchProfile = $this->searchProfile;
/** @var \JobsByMail\Service\Hash $hash */
$hash             = $this->hash;

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>

         
        <?= $this->partial('mail/header', [
            'title'            => 'Suchprofil bestätigen',
            'width'            => $width,
            'mail_blue_color'  => $mail_blue_color,
            'mail_white_color' => $mail_white_color
        ]
        ); ?>
        

            <p>
                Ein "Jobs per Email"-Service wurde angelegt. Nach Bestätigung erhalten sie neue Jobs per Email
                entsprechend ihrem Suchprofil
            </p>

            <p>
                <a href="<?= $this->serverUrl($this->url('lang/jobsbymail/confirm', [
                    'id'   => $searchProfile->getId(),
                    'hash' => $hash->generate($searchProfile)
                ]
                )
                ) ?>"><?= $this->translate('Confirm your search profile.') ?></a>
            </p>
            
            
         <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
      
