<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\User $user */
$user = $this->user;
$width = "600px";
?>
<table class="size margin-auto" style="background-color:#ffffff;max-width:<?=$width?>;width:100%;margin-left: auto;margin-right: auto;">
<tr>
<td align="center" style="text-align: left;padding: 20px 0; font-family:Helvetica,Arial,sans-serif;">
<?= $this->partial('mail/header', ['title' => 'Kennwort zurücksenden', 'width'=>$width]); ?>

<p> Guten Tag <?=$user->getInfo()->getLastName(); ?>,</p>
<p>
um ein neues Passwort für das Bewerbermanagement zu vergeben, klicken Sie bitte auf folgenden Link:
</p>
<p style="width:100%; text-align: center">
<a style="margin-left: auto; margin-right: auto; border-color: #002a80; color: red " href="<?= $this->resetlink; ?>">Link bestätigen</a>
</p>
<p>
Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter zu tun.
<p>
Bitte informieren Sie uns aber, falls Sie Bedenken bezüglich der Sicherheit Ihres Passwortes haben.
</p>
</td></tr></table>
<?= $this->partial('mail/footer', ['width'=>$width]); ?>


