<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\Info $user */
$user = $this->user->getInfo();

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto" style="background-color:<?= $mail_white_color  ?>;max-width:<?=$width?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
            'title' => 'Kennwort zurücksenden',
            'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
            'mail_white_color' => $mail_white_color]); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3>Guten Tag <?=$user->getLastName(); ?>,</h3>
            <p>um ein neues Passwort für das Bewerbermanagement zu vergeben, klicken Sie bitte auf folgenden Link:</p>
            <a style="background-color:<?= $mail_blue_color ?>;padding: 5px 10px 6px 10px;color:<?= $mail_white_color  ?>;text-decoration:none;border-radius:5px;"  href="<?= $this->resetlink; ?>">
                <span style="font-size: 45px;top: 10px;position: relative;">&#8227;</span>
                Link bestätigen
            </a>
            <p>Sollten Sie kein neues Passwort angefordert haben, brauchen Sie nichts weiter zu tun.</p>
            <p>Bitte informieren Sie uns aber, falls Sie Bedenken bezüglich der Sicherheit Ihres Passwortes haben.</p>
            <?= $this->partial('mail/footer', ['width'=>$width, 'mail_white_color'=>$mail_white_color]); ?>
        </div>
    </div>
</div>