<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\User $user */
$width = "600px";
?>
<table class="size margin-auto" style="background-color:#ffffff;max-width:<?=$width?>;width:100%;margin-left: auto;margin-right: auto;">
    <tr>
        <td align="center" style="text-align: left;padding: 20px 0; font-family:Helvetica,Arial,sans-serif;">
<?php echo $this->partial('mail/header', ['title' => 'reset password']); ?>
<p>
    Dear <?=$user->getInfo()->getLastName(); ?>,
</p>
<p>
    please click on the following Link to reset you password:
</p>

<p>
    <a href="<?= $this->resetlink; ?>"><?= $this->resetlink; ?></a>
</p>

<p>
    If you do not have requested for a new password, please just ignore this mail.
</p>
</td></tr></table>
<?= $this->partial('mail/footer.en', array()); ?>
