<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Confirmation Mail to the Customer
 */
$job = $this->job;
/* @var \Jobs\Entity\Job $job */
$user = $job->getUser();
$info = $user->getInfo();

// shared vars used in mails
include_once(__DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
            'title'            => 'Kennwort zurücksenden',
            'width'            => $width,
            'mail_blue_color'  => $mail_blue_color,
            'mail_white_color' => $mail_white_color
        ]
        ); ?>

        <div class="seprate_footer" style="padding:10px;">
            <p><?php echo 'male' == $info->getGender()
                    ? 'Sehr geehrter Herr'
                    : 'Sehr geehrte Frau' ?>
                <?= $info->getDisplayName(/*emailIfEmpty*/
                    false
                ); ?>,</p>

            <p>
                hiermit bestätigen wir Ihnen den Eingang Ihrer Stellenanzeige <b><?= $job->getTitle() ?></b> mit der
                Referenz <b><?= $job->getReference() ?></b>. Sie erhalten von uns eine Nachricht, sobald die Anzeige von
                freigegeben und veröffentlicht wurde.
            </p>

            <p>
                Den aktuellen Status können Sie in der <a
                    href="<?php echo $this->serverUrl() . $this->url('lang/jobs', array('lang' => 'de')) ?>">Job-Übersicht</a>
                verfolgen.
            </p>

            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>