<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2017 Cross Solution (http://cross-solution.de)
 * @license       MIT
 * @author        bleek@cross-solution.de
 */

/** @var \JobsByMail\Entity\SearchProfileInterface $searchProfile */
$searchProfile = $this->searchProfile;
$lang = $searchProfile->getLanguage()?:'de';

/** @var \Core\Options\ModuleOptions $options */
$options  = $this->services('Core/Options');
$siteName = $options->getSiteName();
$operator = $options->getOperator();

/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Zend\View\Helper\ServerUrl $serverUrl */
$serverUrl = $this->plugin('serverUrl');
$serverUrl->setHost($this->host)
          ->setScheme($this->scheme);
/** @var \Zend\View\Helper\BasePath $basePath */
$basePath = $this->plugin('basePath');
$basePath->setBasePath($this->basePath);
/** @var \Zend\Router\Http\TreeRouteStack $router */

$router = $this->services('HttpRouter');
$router->setBaseUrl($this->basePath);

/** @var \JobsByMail\Service\Hash $hash */
$hash = $this->hash;


$unsubscribeUrl = $this->serverUrl(
    $this->url('lang/jobsbymail/unsubscribe',
               [
                   'lang' => $lang,
                   'id'   => $searchProfile->getId(),
                   'hash' => $hash->generate($searchProfile)
               ]
    )
);

$homepageUrl = $this->serverUrl($this->basePath('/'));

$width            = "600px";
$mail_blue_color  = "#295990";
$mail_white_color = "#fff";

?>

<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
                                            'title'            => sprintf('Neue Anzeigen seit %s',
                                                                          $this->dateFormat($searchProfile->getDateLastMail(
                                                                          ), 'short', 'none'
                                                                          )
                                            ),
                                            'width'            => $width,
                                            'mail_blue_color'  => $mail_blue_color,
                                            'mail_white_color' => $mail_white_color
                                        ]
        ); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3>Hallo,</h3>
            <p>neue Jobs seit deinem letzten Besuch.</p>

            <?php foreach ($this->jobs as $job): /** @var \Jobs\Entity\Job $job */ ?>
                <?php

                $jobUrl = $this->jobUrl(
                    $job,
                    [
                        'linkOnly' => true,
                        'absolute' => true
                    ],
                    [
                        'lang' => $lang
                    ]
                );

                $organization    = $job->getOrganization();
                $hasOrganization = $organization && is_object($organization->getOrganizationName());

                ?>
                <!--   Beginning of new jobs   -->

                <table style="vertical-align:top;width:100%">
                    <tbody>
                    <tr>
                        <td style="width:80%;">
                            <p><a href="<?= $jobUrl ?>"><?= $job->getTitle() ?></a></p>
                            <p>
                                <?php if ($hasOrganization
                                          && $organization->getOrganizationName()->getName()
                                ): ?>
                                    <?= $organization->getOrganizationName()->getName() ?>
                                ,
                                <?php endif ?>
                                <?= $job->getLocation() ?>
                            </p>

                        </td>
                        <td style="width:20%;">
                            <p>
                                <?php
                                if ($job->getDatePublishStart()
                                ): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                                elseif ($job->getDateCreated()
                                ): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                                endif
                                ?>
                            </p>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <!--   End of new jobs   -->

            <?php endforeach; ?>

            <p><a href="<?= $unsubscribeUrl ?>">Jobs Mail Service löschen</a></p>

            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>