<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a confirmation link to the user, after registration
 */

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
                                            'title'            => 'Registration',
                                            'width'            => $width,
                                            'mail_blue_color'  => $mail_blue_color,
                                            'mail_white_color' => $mail_white_color
                                        ]
        ); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3>Hallo <?= $this->name; ?>,</h3>

            <p>Ein Account wurde für Sie auf <?= $this->siteName; ?> angelegt.</p>

            <p>Bitte klicken Sie auf folgenden Link, um Ihre Anmeldung zu bestätigen:</p>

            <a style="background-color:<?= $mail_blue_color ?>;padding: 5px 10px 6px 10px;color:<?= $mail_white_color  ?>;text-decoration:none;border-radius:5px;"  href="<?= $this->confirmationlink; ?>">
                <span style="font-size: 45px;top: 10px;position: relative;">&#8227;</span>
                Anmeldung bestätigen
            </a>

            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>
