<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2017 Cross Solution <http://cross-solution.de>
 */
$this->headTitle($this->article->title->rendered);
$this->configHeadScript()->appendFile($this->basePath('/Gastro24/jquery.matchHeight.js'));
$this->configHeadScript()->appendFile($this->basePath('/Gastro24/index.js'));

?>

<div class="container">
  <div class="row">
     <h1><?=$this->article->title->rendered?></h1>
     <hr />
</div>
<div class="wp-content">
    <?=$this->article->content->rendered;?>
</div>
</div>