<?php
/**
 * YAWIK
 *
 * view sript of the start page for unauthenticated users
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

/* @todo Probably, we should create a dedicated IndexController to inject this dependencies. */
$form = $this->services('forms.Jobs/JobboardSearch');
$form->setButtonElement('q');
$form->setAttribute('action', $this->url('lang/jobboard', [], true));

$this->headTitle('Jobs für Gastronomie, Hotel & Tourismus');

?>
<?php $this->headTitle($this->translate('Home'))?>
<div class="jumbotron text-center">

    <h1>Jobs für Gastronomie Fachkräfte</h1>
    <p class="lead">Spannende Jobs für Gastronomie, Hotellerie und Tourismus auf einen Klick finden</p>
    <div class="container">
    <?=$this->searchForm($form);?>
    </div>

</div>

<?php

    $queries = $this->services(\Gastro24\Options\JobsearchQueries::class);




        $tabs = [];
        $sections = [];
        $active = ' active';
        $sectionHtml = '';
        foreach ($queries->getConfig() as $tab => $sections):
            $tabSlug = strtolower(str_replace(' ', '', $tab));
            $tabs[$tabSlug] = $tab;
            $sectionHtml .= '<div class="tab-pane' . $active . '" id="' . $tabSlug . '">
            
            <div class="row">';
            $active='';
            foreach ($sections as $section => $links):
                $sectionHtml .= '<div class="col-md-4"><div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">' . $section . '</h3></div>
<div class="panel-body"><ul>
            ';
                foreach ($links as $name => $params):
                    $sectionHtml .= '<li><a href="' . $this->url('lang/jobboard', [], true) .'?' . $params .'">' . $name .'</a></li>';
                endforeach;
                $sectionHtml .= '</ul></div></div></div>';
            endforeach;
            $sectionHtml .= '</div></div>';
        endforeach;
                

?>

<div class="container">
    <ul class="nav nav-tabs">
        <?php $active=' class="active"'; foreach ($tabs as $slug => $name):?>
        <li<?=$active?>><a href="#<?=$slug?>" data-toggle="tab"><?=$name?></a></li>
        <?php $active=''; endforeach ?>
    </ul>

    <div class="tab-content"><p></p><?=$sectionHtml?></div>

</div>

