<?php
/**
 * YAWIK
 *
 * view sript of the start page for unauthenticated users
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

/* @todo Probably, we should create a dedicated IndexController to inject this dependencies. */
$form = $this->services('forms.Jobs/JobboardSearch');
$form->setButtonElement('q');
$form->setAttribute('action', $this->url('lang/jobboard', [], true));

$this->headTitle('Jobs für Gastronomie, Hotel & Tourismus');
$this->headMeta()->appendName("keywords", "Jobs aus der Gastronomie");
$this->headMeta()->appendName("description", " Gastronomie Jobbörse mit top-aktuellen Gastro Jobs, Hotel & Tourismus Jobs und mehr. Jetzt Traumjob finden - auf einen Klick!");
$this->headScript()->appendFile($this->basePath('Gastro24/jquery.matchHeight.js'))->appendFile($this->basePath('Gastro24/index.js'));

?>

<div id="searchform-wrapper" class="row jumbotron text-center">
    <h1>Jobs für Gastronomie Fachkräfte</h1>
    <p class="lead">Spannende Jobs für Gastronomie, Hotellerie und Tourismus auf einen Klick finden</p>
    <nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
        <div class="search-form-container">
            <?=$this->searchForm($form);?>
        </div>
    </nav>
</div>

<?php

$queries = $this->services(\Gastro24\Options\Landingpages::class);


$tabs = [];
$sections = [];
$active = ' active';
$sectionHtml = '';
foreach ($queries->getTabs() as $tab => $sections):
    $tabSlug = strtolower(str_replace(' ', '', $tab));
    $tabs[$tabSlug] = $tab;
    $sectionHtml .= '<div class="tab-pane' . $active . '" id="' . $tabSlug . '"><div class="row">';
    $active='';
    foreach ($sections as $section => $links):
        $sectionHtml .= '<div class="col-md-4"><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">' .
                        $section . '</h3></div><div class="panel-body"><ul>';

        foreach ($links as $spec):
            $sectionHtml .= '<li><a href="' .
                            $this->url('lang/landingPage', ['q' => $spec[0], 'format' => 'html' ], true) . '">' .
                            $spec[1] .'</a></li>';
        endforeach;
        $sectionHtml .= '</ul></div></div></div>';
    endforeach;
    $sectionHtml .= '</div></div>';
endforeach;
                

?>


<div class="container">
    <ul class="nav nav-tabs">
        <?php $active=' class="active"'; foreach ($tabs as $slug => $name):?>
        <li<?=$active?>><a href="#<?=$slug?>" data-toggle="tab"><?=$name?></a></li>
        <?php $active=''; endforeach ?>
    </ul>
    <div class="tab-content"><p></p><?=$sectionHtml?></div>
</div>
<?php $companies = $queries->getCompanies(); 
if (count($companies)):
    $companies = array_chunk($companies, 6, true);?>
<div id="logos-selected">
 <div class="container">
     <div class="row">
 <h3 class="text-center">Unternehmen mit freien Jobs im Gastrogewerbe</h3>

    <strong>HIER KOMMEN DIE LOGOS DER FIRMEN HIN (ABO BASIC, PLUS UND AUTOPILOT)</strong>

 </div>
</div>
<div>
<?php endif ?>
