<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');


// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('gastrojob24'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName("keywords", "Jobs aus der Gastronomie");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);
$this->configHeadScript()->prependFile($this->basepath('Core/js/core.init.js'));
$this->configHeadScript()->prependFile($this->basePath('Core/js/pnotify.custom.min.js'), 'text/javascript');
$this->configHeadScript()->prependFile($this->basePath('assets/boostrap/bootstrap.min.js'));
$this->configHeadScript()->prependFile($this->basePath('assets/jquery/jquery.min.js'));
$this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/select2.min.js'));
if ($lang!='en') {
    $this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/i18n/' . $lang . '.js'));
}
$this->headLink()->appendStylesheet($this->basePath('/assets/select2/css/select2.css'));
$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/Gastro24/Gastro24.css');
$this->headLink()->prependStylesheet($this->basePath('/Core/css/pnotify.custom.min.css'));

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
<body class="home">
<div class="page">
    <header role="banner">
        <div class="navbar">
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse"
                            type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs menu-logo" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/Gastro24/gastrojob24_blue.svg') ?>" alt="logo" class="menu-logo">
                    </a>
                    <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">G24</a>
                </div>
                <?php
                echo $this->navigation('Core/Navigation')
                          ->setAcl($this->services('acl'))
                          ->setRole($this->auth('role'))
                          ->menu()
                          ->setMaxDepth(0) // only show the top level entries
                          ->renderPartial(null, 'main-navigation');
//                          ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>
                <?php #echo $this->loginInfo() ?>
            </nav>
            <!-- /main-navigation -->
        </div>
    </header>
</div>

<main id="content" class="col-md-12">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<footer id="footer">
 <div class="container">
    <div class="row">
  </div>
         <div class="container">
             <div class="row">
                 <div class="col-sm-6 col-md-3 col-xs-12">
                     <div class="footer_block">

                         <h4>Gastrojob24</h4>

                         <ul class="footer-links">
                             <li> <a href="#">Kontakt</a> </li>
                             <li> <a href="#">Impressum</a> </li>
                             <li> <a href="#">Disclaimer</a> </li>
                             <li> <a href="#">Über uns</a> </li>


                         </ul>

                     </div>
                 </div>
                 <div class="col-sm-6 col-md-3 col-xs-12">
                     <div class="footer_block">
                         <h4>Arbeitgeber</h4>

                         <ul class="footer-links">
                             <li> <a href="#">Merkliste</a> </li>
                             <li> <a href="#">About Us</a> </li>
                             <li> <a href="#">Privacy</a> </li>
                             <li> <a href="#">Contact Us</a> </li>
                             <li> <a href="#">Term & Conditions</a> </li>
                         </ul>


                     </div>
                 </div>
                 <div class="col-sm-6 col-md-3 col-xs-12">
                     <div class="footer_block">
                         <h4>Jobsuche</h4>

                         <ul class="footer-links">
                             <li> <a href="#">Merkliste</a> </li>
                             <li> <a href="#">About Us</a> </li>
                             <li> <a href="#">Privacy</a> </li>
                             <li> <a href="#">Contact Us</a> </li>
                             <li> <a href="#">Term & Conditions</a> </li>
                         </ul>



                     </div>
                 </div>
                 <div class="col-sm-6 col-md-3 col-xs-12">
                     <div class="footer_block">
                         <h4>Beliebte Suchanfragen</h4>

                         <ul class="footer-links">
                             <li> <a href="#">Merkliste</a> </li>
                             <li> <a href="#">About Us</a> </li>
                             <li> <a href="#">Privacy</a> </li>
                             <li> <a href="#">Contact Us</a> </li>
                             <li> <a href="#">Term & Conditions</a> </li>
                         </ul>

                         <?=$this->languageSwitcher()?>
                     </div>
                 </div>

             </div>
         </div>
</footer>
<section class="footer-bottom-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="footer-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <h3>Haben Sie Fragen?</h3>
                                <h4>Rufen Sie uns an: <strong>+41 71 310 10 08</strong>. Wir helfen Ihnen gerne weiter!</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php echo $this->partial("piwik") ?>
</body>
</html>
