<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');


// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);
$this->configHeadScript()->prependFile($this->basepath('Core/js/core.init.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/pnotify/pnotify.custom.min.js'), 'text/javascript');
$this->configHeadScript()->prependFile($this->basePath('/assets/bootstrap/js/bootstrap.min.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/jquery/jquery.min.js'));
$this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/select2.min.js'));
if ($lang!='en') {
    $this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/i18n/' . $lang . '.js'));
}
$this->headLink()->appendStylesheet($this->basePath('/assets/select2/css/select2.css'));
$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/Gastro24/Gastro24.css');
$this->headLink()->prependStylesheet($this->basePath('/assets/pnotify/pnotify.custom.min.css'));
$this->headLink()->prependStylesheet('/blog/wp-content/plugins/dk-pricr-responsive-pricing-table/css/rpt_style.min.css?ver=4.7.5');

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MCDJ26Q');</script>
    <!-- End Google Tag Manager -->
</head>
<body class="home">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCDJ26Q"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="wrapper">
    <header id="header" role="banner">
        <div class="navbar">
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse"
                            type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs menu-logo" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/Gastro24/gastrojob24_white.svg') ?>" alt="Gastrojob24 Schweiz" class="menu-logo">
                    </a>
                    <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">G24</a>
                </div>

                <?= $this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
//                         ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>
            </nav>
            <!-- /main-navigation -->
        </div>
        <div id="formular">
        </div>
    </header>
    <div class="scroll-arrow" style="display: none;">
        <span class="arrow-icon"></span>
    </div>
</div>

<main id="content">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<!--
 <?= $this->wordpress()->menu('YAWIK-Seiten') ?>
 <?=$this->languageSwitcher()?>
-->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <h5>Über Gastrojob24</h5>
                <nav>
                    <ul class="list-unstyled">
                        <li><a title="" href="/de/wp/page/ueber-uns">Wer wir sind</a></li>
                        <li><a title="" href="/de/wp/page/partnernetzwerk">Partnernetzwerk</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-2">
                <h5>Social Media</h5>
                <nav>
                    <ul class="list-unstyled">
                        <li><a title="Gastrojob24.ch bei Facebook" href="https://www.facebook.com/gastrojob24.ch/" target="_blank">Facebook</a></li>
                        <li><a title="Gastrojob24.ch bei Twitter" href="https://twitter.com/Gastrojob24_CH" target="_blank">Twitter</a></li>

                    </ul>
                </nav>
            </div>
            <div class="col-md-2">
                <h5>Für Arbeitgeber</h5>
                <nav>
                    <ul class="list-unstyled">
                        <li><a title="Login für Arbeitgeber" href="<?=$this->url('lang/auth', [], true)?>">Login</a></li>
                        <li><a title="Registrieren" href="<?=$this->url('lang/auth',[],  true)?>#register">Registieren</a></li>
                        <li><a title="Preise & Leistungen" href="/de/wp/page/stellenanzeigen-schalten">Preise & Leistungen</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-offset-3 col-md-3">
                <!--<h5>International</h5>-->

            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-12 text-center">
                <nav>
                    <ul class="list-inline">
                        <li><a title="Impressum" href="/de/wp/page/impressum">Impressum</a></li>
                        <li><a title="AGB" href="/de/wp/page/agb">AGB</a></li>
                        <li><a title="Kontakt" href="/de/wp/page/kontakt">Kontakt</a></li>
                    </ul>
                </nav>
                <p>Copyright &copy; Gastrojob24 2003 - 2018</p>
            </div>
        </div>
</footer>
<?php echo $this->partial("piwik") ?>
</body>
</html>
