<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');


// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);
$this->configHeadScript()->prependFile($this->basepath('Core/js/core.init.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/pnotify/pnotify.custom.min.js'), 'text/javascript');
$this->configHeadScript()->prependFile($this->basePath('/assets/bootstrap/js/bootstrap.min.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/jquery/jquery.min.js'));
$this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/select2.min.js'));
if ($lang!='en') {
    $this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/i18n/' . $lang . '.js'));
}
$this->headLink()->appendStylesheet($this->basePath('/assets/select2/css/select2.css'));
$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/Gastro24/Gastro24.css');
$this->headLink()->prependStylesheet($this->basePath('/assets/pnotify/pnotify.custom.min.css'));
$this->headLink()->prependStylesheet('/blog/wp-content/plugins/dk-pricr-responsive-pricing-table/css/rpt_style.min.css?ver=4.7.5');

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MCDJ26Q');</script>
    <!-- End Google Tag Manager -->
</head>
<body class="home">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCDJ26Q"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="page">
    <header role="banner">
        <div class="navbar">
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse"
                            type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs menu-logo" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/Gastro24/gastrojob24_blue.svg') ?>" alt="Gastrojob24 Schweiz" class="menu-logo">
                    </a>
                    <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">G24</a>
                </div>

                <?= $this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
//                         ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>
            </nav>
            <!-- /main-navigation -->
        </div>
    </header>
</div>

<main id="content" class="col-md-12">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<footer id="footer">
         <div class="container">
             <div class="row">
			   <div class="col-sm-6 col-md-4 col-xs-12">
                     <div class="footer_block">
                         Gastrojob24.ch
						 
			

            <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                <ul class="footer__bankAddress">
                    <li itemprop="streetAddress">Kastenberg 1</li>
                    <li>
                        <div itemprop="postalCode">9312</div>
                        <div itemprop="addressLocality">Häggenschwil</div>
                    </li>
                    <li class="is-hidden" itemprop="addressRegion" aria-hidden="true">SG</li>
                    <li class="is-hidden" itemprop="addressCountry" aria-hidden="true">CH</li>
                </ul>
            </address>

            
                <ul class="footer__bankContact">
                    <li itemprop="telephone">Tel. <a href="tel:+41813071111"><span class="footer__bankContactTel">+41813071111</span></a></li>
                    <li itemprop="email"><a class="footer__link" href="mailto:info@gastrojob24.ch"><span>info@gastrojob24.ch</span></a></li>
                 
                </ul>

                        
						<div class="footer__copyright" itemscope itemtype="http://schema.org/WebPage">
							<span itemprop="copyrightYear">2008 - 2017</span>
							<span itemprop="copyrightHolder">Gastrojob24</span>
						</div>
                     
                     </div>
                 </div>

                 <div class="col-sm-6 col-md-4 col-xs-12">
                     <div class="footer_block">

                         <ul class="footer-links">
                             <li> <a href="<?=$this->url('lang/auth', [], true)?>">Arbeitgeber Login</a> </li>
                             <li> <a href="<?=$this->url('lang/auth',[],  true)?>#register">Registrieren</a> </li>
                            
                         </ul>


                     </div>
                 </div>
                 <div class="col-sm-6 col-md-4 col-xs-12">
                     <div class="footer_block">

                         <?= $this->wordpress()->menu('YAWIK-Seiten') ?>

                     </div>
                 </div>
               
             </div>
         </div>
		 
    <div id="social-media">
	
  <div class="container">
             <div class="row">
			 
			     <?=$this->languageSwitcher()?>
			 <ul class="social-media-links">
                             <li> <a href="http://haubenhero.de"> <span class="fa fa-facebook fa-fw"></span> Facebook  </a> </li>
							<li> <a href="http://haubenhero.de"> <span class="fa fa-twitter fa-fw"></span> Twitter  </a> </li>
							<li> <a href="http://haubenhero.de"> <span class="fa fa-twitter fa-fw"></span> weltweit  </a> </li>
                             <li> <a href="http://gastrojob24.at">gastrojob24.at</a> </li>
							 
			 </ul>
       </div>                 

	
	</div>
	</div>
</footer>
<?php echo $this->partial("piwik") ?>
</body>
</html>
