<!-- Piwik -->
<script type="text/javascript">
    var _paq = _paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u="//count.mediaintown.de/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
<?php
if ($this->auth()->isLoggedIn()){
  echo '_paq.push([\'setUserId\',\''.$this->auth('info')->getDisplayName().'\']);';
}
?>
        _paq.push(['setSiteId', '24']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<!-- End Piwik Code -->