<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');


// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->setAllowArbitraryAttributes(true);
$this->configHeadScript()->prependFile($this->basepath('Core/js/core.init.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/pnotify/pnotify.custom.min.js'), 'text/javascript');
$this->configHeadScript()->prependFile($this->basePath('/assets/bootstrap/js/bootstrap.min.js'));
$this->configHeadScript()->prependFile($this->basePath('/assets/jquery/jquery.min.js'));
$this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/select2.min.js'));
if ($lang!='en') {
    $this->configHeadScript()->appendFile($this->basePath('/assets/select2/js/i18n/' . $lang . '.js'));
}
$this->headLink()->appendStylesheet($this->basePath('/assets/select2/css/select2.css'));
$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/Gastro24/Gastro24.css');
$this->headLink()->prependStylesheet($this->basePath('/assets/pnotify/pnotify.custom.min.css'));
$this->headLink()->prependStylesheet('/blog/wp-content/plugins/dk-pricr-responsive-pricing-table/css/rpt_style.min.css?ver=4.7.5');

foreach ($languages as $lang) {
    $this->headLink()->appendAlternate(
        preg_replace('~^'.$this->basepath('/'.$this->params('lang')).'~',
            $this->basepath('/'.$lang),$_SERVER['REQUEST_URI']),
        'hreflang',
        $this->headTitle()->setTranslator()->renderTitle() ,
        array('hreflang'=>$lang));
}
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <script>
        <!--
        jQuery( document ).ready(function() {
            /* Scroll-Icon */

            if (jQuery(document).scrollTop() > 500) {
                jQuery('.scroll-arrow').fadeOut();
            }
            jQuery('.scroll-arrow').click(function(){
                jQuery('html,body').animate({scrollTop: jQuery('#content').offset().top }, 600, 'linear');
            });
        });

        jQuery(window).scroll(function() {

            if (jQuery(document).scrollTop() > 500) {
                jQuery('.scroll-arrow').fadeOut();
            }
        });
        //-->
    </script>
    <?php echo $this->configHeadScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MCDJ26Q');</script>
    <!-- End Google Tag Manager -->

</head>
<body class="home">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCDJ26Q"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="wrapper">
    <div id="bg-full">
        <span class="bg-static"></span>
    </div>
    <header id="header" class="startpage" role="banner">
        <div class="navbar">
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".navbar-collapse" data-toggle="collapse"
                            type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs menu-logo" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/Gastro24/gastrojob24_white.svg') ?>" alt="Gastrojob24 Schweiz" class="menu-logo">
                    </a>
                    <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">G24</a>
                </div>

                <?= $this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
//                         ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>
            </nav>
            <!-- /main-navigation -->
        </div>
        <?php
        /* @todo Probably, we should create a dedicated IndexController to inject this dependencies. */
        $form = $this->services('forms.Jobs/JobboardSearch');
        $form->setButtonElement('q');
        $form->setAttribute('action', $this->url('lang/jobboard', [], true));

        ?>
        <div class="container jumbotron text-center">
            <h1>Jobs für Gastronomie Fachkräfte</h1>
            <p class="lead">Spannende Jobs für Gastronomie, Hotellerie und Tourismus auf einen Klick finden</p>
            <nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
                <div class="search-form-container">
                    <?=$this->searchForm($form);?>
                </div>
            </nav>
        </div>
    </header>
    <div class="scroll-arrow">
        <span class="arrow-icon"></span>
    </div>
</div>

<?php

$queries = $this->services(\Gastro24\Options\Landingpages::class);
$this->headTitle($this->translate('Home'));

?>

<main id="content">
    <?php echo $notifications?>
    <?php $companies = $queries->getCompanies();?>
    <?php if (count($companies)):
    $companies = array_chunk($companies, 6, true);?>
    <div id="logos-selected">
        <div class="container">
            <div class="row">
                <h2 class="text-center">Unternehmen mit freien Gastronomie Stellen</h2>
                <div id="companies-slider" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <?php for ($i=0, $c=count($companies); $i<$c; $i+=1):?>
                            <li<?=0===$i ? ' class="active"' : '' ?> style="background-color: #666;" data-target="#companies-slider" data-slide-to="<?=$i?>"></li>
                        <?php endfor ?>
                    </ol>

                    <div class="carousel-inner">
                        <?php $active=" active";
                        foreach ($companies as $comps):?>
                            <div class="item<?=$active?> container">
                                <div class="row">
                                    <?php foreach ($comps as $term => $spec):?>
                                        <div class="col-md-2">
                                            <a href="<?=$this->url('lang/landingPage', ['q' => $term, 'format' => 'html' ], true) ?>">
                                <div class="frame">
                                <?php if ($spec[1]): ?>
                                    <img src="<?=$spec[1]?>" alt="<?=$spec[0]?>" >
                                <?php else: ?>
                                    <?=$spec[0]?>
                                <?php endif ?>
                                </div></a>
                                        </div>
                                    <?php endforeach ?>
                                </div>
                            </div>
                            <?php $active = ''; endforeach ?>
                    </div>
                </div>
            </div>
        </div>
   </div>
    <?php endif ?>



    <div class="container">
        <?php

        $tabs = [];
        $sections = [];
        $active = ' active';
        $sectionHtml = '';
        foreach ($queries->getTabs() as $tab => $sections):
            $tabSlug = strtolower(str_replace(' ', '', $tab));
            $tabs[$tabSlug] = $tab;
            $extra_css=($tab=="Jobs in deiner Region")?' region ':'';
            $sectionHtml .= '<hr><h2 class="text-center">' . $tab . '</h2><div class="row">';
            $active='';
            foreach ($sections as $section => $links):
                if ($tab == 'Jobs in deiner Region') {
                    $sectionHtml .= '<div class="region"><ul>';
                }else {
                    $sectionHtml .= '<div class="col-md-4' . $extra_css . '"><h3>'. $section .'</h3><ul>';
                }
                foreach ($links as $spec):
                    $sectionHtml .= '<li><a href="' .
                                    $this->url('lang/landingPage', ['q' => $spec[0], 'format' => 'html' ], true) . '">' .
                                    $spec[1] .'</a></li>';
                endforeach;
                $sectionHtml .= '</ul></div>';
            endforeach;
            $sectionHtml .= '</div>';
        endforeach;

        ?>
        <div class="container">
            <?=$sectionHtml?>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-center">Jobs schalten und noch heute geeignete Bewerbungen erhalten</h2>

                <a href="de/wp/page/stellenanzeigen-schalten" class="btn-block-sm margin-top-smaller btn btn-primary btn-large outline">
                    <span>Jetzt Job inserieren</span>
                </a>
                <p class="margin-top-small text-small text-muted">Kostenlos bis März 2018 Jobs insieren</p>

                <div class="col-md-4">
                    <h3 class="h6">Hohe Reichweite</h3>
                    <p>Ein Job-Inserat, viele Kanäle: Partnernetzwerk, Jobmail-Newsletter, Suchmaschinen und Social Media.</p>

                </div>
                <div class="col-md-4">
                    <h3 class="h6">Bewerbermanagement & Jobprofil</h3>
                    <p>Umfangreiches Bewerbermanagement-System mit Statistiken, E-Mail Vorlagen für Zu- und Absagen, Job-Templates und Vielem mehr. </p>

                </div>
                <div class="col-md-4">
                    <h3 class="h6">Einfach & günstig</h3>
                    <p>Unkompliziert Jobs inserieren: Bequem mit Kreditkarte, PayPal oder Rechnung bezahlen.</p>

                </div>
            </div>
        </div>
    </div>
</main>
<!-- /container -->
<!--
 <?= $this->wordpress()->menu('YAWIK-Seiten') ?>
 <?=$this->languageSwitcher()?>
-->
<?php echo $this->partial("footer") ?>
<?php echo $this->partial("piwik") ?>
</body>
</html>
